# Default configuration for Email Priority Manager

# Basic settings
debug: false
environment: development

# Data and log directories
data_dir: "./data"
log_dir: "./logs"
temp_dir: "./temp"

# Database configuration
database:
  path: "email_priority.db"
  backup_enabled: true
  backup_interval: 86400  # 24 hours in seconds
  backup_count: 7
  echo: false
  pool_size: 5
  max_overflow: 10

# Email processing configuration
processing:
  batch_size: 10
  max_email_size: 10485760  # 10MB
  allowed_file_types:
    - "pdf"
    - "doc"
    - "docx"
    - "txt"
    - "rtf"
  scan_interval: 300  # 5 minutes in seconds
  priority_threshold: 0.5

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "email_priority.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5