# Logging configuration for Email Priority Manager

version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  simple:
    format: '%(levelname)s: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: ~/.email_priority_manager/logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: ~/.email_priority_manager/logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

loggers:
  email_priority_manager:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false

  email_priority_manager.database:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  email_priority_manager.ai:
    level: INFO
    handlers: [console, file]
    propagate: false

  email_priority_manager.cli:
    level: INFO
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console]